version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Database Configuration
      - VITE_DB_CLIENT=${VITE_DB_CLIENT:-pg}
      - VITE_DB_HOST=${DB_HOST:-db}
      - VITE_DB_PORT=${DB_PORT:-5432}
      - VITE_DB_USER=${DB_USER:-jboilerplate}
      - VITE_DB_PASSWORD=${DB_PASSWORD:-jboilerplate}
      - VITE_DB_NAME=${DB_NAME:-jboilerplate}
      - VITE_DB_SSL=${VITE_DB_SSL:-false}
      # API Configuration
      - VITE_API_URL=${VITE_API_URL:-}
      - VITE_API_TIMEOUT=${VITE_API_TIMEOUT:-30000}
      # Feature Flags
      - VITE_FEATURE_DARK_MODE=${VITE_FEATURE_DARK_MODE:-true}
      - VITE_FEATURE_MULTILINGUAL_SUPPORT=${VITE_FEATURE_MULTILINGUAL_SUPPORT:-true}
      - VITE_FEATURE_NOTIFICATIONS=${VITE_FEATURE_NOTIFICATIONS:-true}
      - VITE_FEATURE_ANALYTICS=${VITE_FEATURE_ANALYTICS:-false}
      - VITE_FEATURE_ADMIN_DASHBOARD=${VITE_FEATURE_ADMIN_DASHBOARD:-true}
      - VITE_FEATURE_USER_MANAGEMENT=${VITE_FEATURE_USER_MANAGEMENT:-true}
      - VITE_FEATURE_EMAIL_SERVICE=${VITE_FEATURE_EMAIL_SERVICE:-false}
    ports:
      - "${WEB_PORT:-3100}:80"
    volumes:
      - app_logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    profiles:
      - default
      - with-db

  db:
    image: ${DB_IMAGE:-postgres:16}
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_ROOT_PASSWORD:-rootpassword}
      - POSTGRES_DB=${DB_NAME:-jboilerplate}
      - POSTGRES_USER=${DB_USER:-jboilerplate}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT_FORWARD:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-jboilerplate} -d ${DB_NAME:-jboilerplate}"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - with-db

volumes:
  postgres_data:
    driver: local
  app_logs:
    driver: local 